/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2024-03-22 07:00:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import model.Machines;
import model.Member;
import model.Trainer;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Date;
import javax.xml.crypto.Data;

public final class adminHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1705867853722L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Trainer");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("model.Machines");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("javax.xml.crypto.Data");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("model.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Gym Management</title>\r\n");
      out.write(" <link rel=\"icon\" href=\"img/gm.jpg\" type=\"image/jpg\" />\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"JS/chart.js\"></script><link rel=\"stylesheet\" href=\"css/trainer.css\">\r\n");
      out.write("<script src=\"js/member.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"text-start bg-dark\">\r\n");
      out.write("<!-- navbar -->\r\n");
      out.write("<div class=\"sticky-top\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg  navbar-dark bg-secondary \">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarTogglerDemo03\" aria-controls=\"navbarTogglerDemo03\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\"><b><i>Gym Management</i></b></a>\r\n");
      out.write("    <div class=\"collapse navbar-collapse text-end\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"home\">Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("     \r\n");
      out.write("        <li class=\"nav-item dropdown \">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Trainer Details\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"tList\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Trainer List</button>\r\n");
      out.write("      </form>\r\n");
      out.write("      </li>\r\n");
      out.write("             <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"addTra\" method=\"post\">\r\n");
      out.write("        		<button style=\"border: none;outline: none;\">Add New Trainer</button>\r\n");
      out.write("      			</form>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"tModify\" method=\"post\">\r\n");
      out.write("        		<button style=\"border: none;outline: none;\">Modify Trainer Details</button>\r\n");
      out.write("      			</form></li>\r\n");
      out.write("             <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"tdel\" method=\"post\">\r\n");
      out.write("        		<button style=\"border: none;outline: none;\">Delete Trainer Details</button>\r\n");
      out.write("      			</form></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("         <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Member Details\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"mList\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Member List</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("             <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"addMem\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Add New Member</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"memCheck\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Modify Member Details</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("             <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"memdel\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Delete Member Details</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      \r\n");
      out.write("       <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Machine Details\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"mmList\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Machine List</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("             <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"addMach\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Add Machine Details</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"mechModify\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Modify Machine Details</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("             <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"mechDel\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Delete Machine Details</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("         <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Machine Booking\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("           <li><form class=\"d-flex dropdown-item\" action=\"blist\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\"> Booking Details</button>\r\n");
      out.write("      </form></li> <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"mbook\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Book a machine</button> \r\n");
      out.write("      </form></li>\r\n");
      out.write("             <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"cbook\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">Cancel Booking </button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            \r\n");
      out.write("             <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"seeReserv\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\">See Reservation`s</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("      <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><form class=\"d-flex dropdown-item\" action=\"#\" method=\"post\">\r\n");
      out.write("        <button style=\"border: none;outline: none;\"> Reset Reservations</button>\r\n");
      out.write("      </form></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("         <li class=\"nav-item mx-2\">\r\n");
      out.write("          <a href=\"https://www.instagram.com/vijaybodare_/?next=https%3A%2F%2Fwww.instagram.com%2Faccounts%2Fonetap%2F%3Fnext%3D%252Faccounts%252Flogout%252F%26__coig_login%3D1\" title=\"Instagram\" target=\"_blank\"><img src=\"./img/inshtagram.jpg\" style=\"height: 35px;width:35px;border-radius: 100px 100px;\" alt=\"not found\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("         <li class=\"nav-item mx-1\">\r\n");
      out.write("         <a href=\"https://www.facebook.com/vijaybodare1403s2000\" title=\"Facebook\" target=\"_blank\"><img src=\"./img/facebook.jpg\" style=\"height: 35px;width:35px;border-radius: 100px 100px;\" alt=\"not found\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("         <li class=\"nav-item mx-1\">\r\n");
      out.write("         <a href=\"https://api.whatsapp.com/send/?phone=%2B918408031080&text&type=phone_number&app_absent=0\" title=\"WhatsApp\" ><img src=\"./img/whatapp.jpg\" style=\"height: 35px;width:35px;border-radius: 100px 100px;\" alt=\"not found\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </div>\r\n");
      out.write("     \r\n");
      out.write("    <div class=\"d-flex\" style=\"height: 30px;width: 200px\"><marquee><span class=\"text text-danger fs-4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgReg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></marquee></div>\r\n");
      out.write("    <div class=\"d-flex mx-1\" >\r\n");
      out.write("    <form action=\"logout\" method=\"post\">\r\n");
      out.write("        <button title=\"Click To Logout\" class=\"btn btn-danger\" style=\"width: 150px;border-radius: 25px 0px 25px 0px;\">\r\n");
      out.write("        <span class=\"fs-3 text-info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${op}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>&nbsp;\r\n");
      out.write("        	<span class=\"fs-4 text-warning\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>&nbsp;\r\n");
      out.write("    	<span class=\"fs-3 text-info\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("	<div class=\"container-lg\" >\r\n");
      out.write("	");

	
	try{
		String back=(String)request.getAttribute("back");
	
		if(back == null)
		{
	
      out.write(" <br>\r\n");
      out.write("	<div class=\"container my-2\" >\r\n");
      out.write("		\r\n");
      out.write("	   <img alt=\"not\" src=\"https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg\" style=\"height: 450px;width: 100%; text-align: center;opacity: 0.4\">\r\n");
      out.write("	</div>\r\n");

		}
	
	}catch(Exception e)
	{
		e.printStackTrace();
	}


      out.write("\r\n");
      out.write("	<table  class=\"table table-hover table-dark table-bordered\">\r\n");
      out.write("	\r\n");
      out.write("	 ");

		  	 Connection con=null;
		  
			  try {
					con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gym","root","shiv@123");
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
		  
		  PreparedStatement ps;
		  ResultSet rs;
		  ArrayList<Trainer> tli=new ArrayList<Trainer>();
		  ArrayList<Machines> mlishow=new ArrayList<Machines>();
		  ArrayList<Machines> mbookli=new ArrayList<Machines>();
		  Trainer tl;
		  Machines ml;
		  Machines mbl;
		  String getTname="SELECT tname,tcontact FROM trainer";
		  String getm="SELECT mname FROM machines";
		  String getmboking="SELECT * FROM machine_booking";
		  try{
				 ps= con.prepareStatement(getTname);
				rs=ps.executeQuery();
				while(rs.next()){
					tl=new Trainer(rs.getString(1),rs.getString(2));
					tli.add(tl);
				}
				ps= con.prepareStatement(getm);
				rs=ps.executeQuery();
				while(rs.next()){
					ml=new Machines(rs.getString(1));
					mlishow.add(ml);
				}
				ps= con.prepareStatement(getmboking);
				rs=ps.executeQuery();
				while(rs.next()){
					mbl=new Machines(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4));
					mbookli.add(mbl);
				}
		  }catch(Exception e){e.printStackTrace();}
				  
		  
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	");

	
	try{
		ArrayList<Trainer> tlist=(ArrayList<Trainer>)request.getAttribute("tlist");
		String tmodify=(String)request.getAttribute("tmodify");
		String tFound=(String)request.getAttribute("tFound");
		String tdel=(String)request.getAttribute("tdel");
		ArrayList<Member> mlist=(ArrayList<Member>)request.getAttribute("mlist");
		ArrayList<Machines> mmlist=(ArrayList<Machines>)request.getAttribute("mmlist");
		ArrayList<Machines> blist=(ArrayList<Machines>)request.getAttribute("blist");
		String mbook=(String)request.getAttribute("mbook");
		String mbookingForm=(String)request.getAttribute("mbookingForm");
		String cbook=(String)request.getAttribute("cbook");
		String seeReserv=(String)request.getAttribute("seeReserv");
		ArrayList<Machines> seeList=(ArrayList<Machines>)request.getAttribute("seeList");
		String addMach=(String)request.getAttribute("addMach");
		String mechModify=(String)request.getAttribute("mechModify");
		String mechDel=(String)request.getAttribute("mechDel");
		String addTra=(String)request.getAttribute("addTra");
		String addMem=(String)request.getAttribute("addMem");
		String memCheck=(String)request.getAttribute("memCheck");
		String getmemUpForm=(String)request.getAttribute("getmemUpForm");
		String memdel=(String)request.getAttribute("memdel");
		
		if(tlist!=null)
		{
	
      out.write(" \r\n");
      out.write("	<h3 class=\"text text-light\">Trainer List</h3>\r\n");
      out.write("	<thead class=\"text text-center \">\r\n");
      out.write("    		<tr>\r\n");
      out.write("				<th scope=\"col\">ID</th>\r\n");
      out.write("				<th scope=\"col\">Profile</th>\r\n");
      out.write("				<th scope=\"col\">Trainer Name</th>\r\n");
      out.write("				<th scope=\"col\">Trainer Contact</th>\r\n");
      out.write("				<th scope=\"col\">Gender</th>\r\n");
      out.write("			 </tr>\r\n");
      out.write(" 	 </thead>\r\n");
      out.write("	");

		for(Trainer t:tlist)
		{
			
		
      out.write("\r\n");
      out.write("		<tbody class=\"text text-center text-secondary\">\r\n");
      out.write("            <tr>\r\n");
      out.write("            <th scope=\"row\">");
      out.print(t.getTid());
      out.write("</th>\r\n");
      out.write("            <td><img style=\"height: 50px;width: 80px;border-radius: 10px 10px\" alt=\"not Found\" src=\"img/tProfile/");
      out.print(t.gettProfile());
      out.write("\"></td>\r\n");
      out.write("            <td>");
      out.print(t.getTname() );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(t.getTcontact());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(t.getTgender() );
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</tbody>\r\n");
      out.write("		");


		}
		}
		
	
		if(mlist!=null)
		{
	
      out.write(" \r\n");
      out.write("	<h3 class=\"text text-light \">Member List</h3>\r\n");
      out.write("	<thead class=\"text text-center\">\r\n");
      out.write("    		<tr>\r\n");
      out.write("				<th scope=\"col\">ID</th>\r\n");
      out.write("				<th scope=\"col\">Fist Name</th>\r\n");
      out.write("				<th scope=\"col\">Last Name</th>\r\n");
      out.write("				<th scope=\"col\">Gender</th>\r\n");
      out.write("				<th scope=\"col\">Contact</th>\r\n");
      out.write("				<th scope=\"col\">Weight-(KG)</th>\r\n");
      out.write("				<th scope=\"col\">Height-(Feet)</th>\r\n");
      out.write("				<th scope=\"col\">Program</th>\r\n");
      out.write("				<th scope=\"col\">Trainer Name</th>\r\n");
      out.write("				<th scope=\"col\">Session</th>\r\n");
      out.write("				<th scope=\"col\">Membership</th>\r\n");
      out.write("			 </tr>\r\n");
      out.write(" 	 </thead>\r\n");
      out.write("	");

		for(Member m:mlist)
		{
			
		
      out.write("\r\n");
      out.write("		<tbody class=\"text text-center text-secondary\">\r\n");
      out.write("            <tr>\r\n");
      out.write("            <th scope=\"row\">");
      out.print(m.getMid());
      out.write("</th>\r\n");
      out.write("			<td>");
      out.print( m.getMfname());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(m.getMlname());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( m.getMgender());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(m.getMcontact() );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( m.getMweight());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(m.getMheight() );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( m.getMprogram());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(m.getMtrainer());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( m.getMsession());
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( m.getMmembership());
      out.write("</td>\r\n");
      out.write("			\r\n");
      out.write("		</tr>\r\n");
      out.write("	</tbody>\r\n");
      out.write("		");


		}
		}
		
	if(mmlist!=null)
	{

      out.write(" \r\n");
      out.write("<h3 class=\"text text-light \">Machines List</h3>\r\n");
      out.write("<thead class=\"text text-center\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th scope=\"col\">ID</th>\r\n");
      out.write("			<th scope=\"col\">Machine Name</th>\r\n");
      out.write("			<th scope=\"col\">Available`s Booking </th>\r\n");
      out.write("			\r\n");
      out.write("		 </tr>\r\n");
      out.write("	 </thead>\r\n");


	for(Machines mm:mmlist)
	{
		
	
      out.write("\r\n");
      out.write("	<tbody class=\"text text-center text-secondary\">\r\n");
      out.write("        <tr>\r\n");
      out.write("        <th scope=\"row\">");
      out.print(mm.getMid());
      out.write("</th>\r\n");
      out.write("		<td>");
      out.print( mm.getMname());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print( mm.getBooking());
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("	");


	}
	}
	
	if(addTra!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Add Trainers</span>\r\n");
      out.write("      <form action=\"tReg\" autocomplete=\"on\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" required oninput=\"trainer()\" name=\"tname\" placeholder=\"Trainer Name\" aria-label=\"First name\" >\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row my-2\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" required oninput=\"trainer()\" name=\"tcon\" placeholder=\"Trainer Contact\" aria-label=\"phone name\">\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("			 	<button><input type=\"file\" name=\"img\" id=\"img\"></button>\r\n");
      out.write("			  \r\n");
      out.write("			<div class=\"row my-2\">\r\n");
      out.write("			<div class=\"col\">\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"tgen\" id=\"inlineRadio1\" value=\"male\">\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio1\">Male</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"tgen\" id=\"inlineRadio2\" value=\"female\">\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio2\">Female</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"tgen\" id=\"inlineRadio3\" value=\"other\" >\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio3\">Other</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-success\">Register</button>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	if(tmodify!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Check Trainer Data</span>\r\n");
      out.write("      <form method=\"post\" action=\"tcheck\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" required oninput=\"trainer()\" name=\"tnames\" placeholder=\"Trainer Name\" aria-label=\"First name\" >\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row my-2\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" required oninput=\"trainer()\" name=\"tcont\" placeholder=\"Trainer Contact\" aria-label=\"phone name\">\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-warning\">Check Data</button>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	
	if(tFound!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Update Trainers Data</span>\r\n");
      out.write("      <form method=\"post\" action=\"tup\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" required oninput=\"trainer()\" name=\"tname\" placeholder=\"Trainer Name\" aria-label=\"First name\" >\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row my-2\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" required oninput=\"trainer()\" name=\"tcon\" placeholder=\"Trainer Contact\" aria-label=\"phone name\">\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row my-2\">\r\n");
      out.write("			<div class=\"col\">\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"tgen\" id=\"inlineRadio1\" value=\"male\">\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio1\">Male</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"tgen\" id=\"inlineRadio2\" value=\"female\">\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio2\">Female</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"tgen\" id=\"inlineRadio3\" value=\"other\" >\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio3\">Other</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-secondary\">Update Data</button>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("	");


	}
	
	if(tdel!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Delete Data</span>\r\n");
      out.write("      <form method=\"post\" action=\"tdelete\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("		  <select class=\"form-select\" name=\"tname\" id=\"tname\" aria-label=\"Default select example\" required>\r\n");
      out.write("			  <option selected value=\"\">Select Name :</option>\r\n");
      out.write("			\r\n");
      out.write("			  ");

			  if(tli!=null){
				  for(Trainer t:tli)
				  {
			  
      out.write("\r\n");
      out.write("			  <option name=\"");
      out.print(t.getTname() );
      out.write("\" id=\"");
      out.print(t.getTname() );
      out.write("\" value=\"");
      out.print(t.getTname() );
      out.write('"');
      out.write('>');
      out.print(t.getTname().toUpperCase() );
      out.write(" -- ");
      out.print(t.getTcontact().toString().toLowerCase());
      out.write("</option>\r\n");
      out.write("			\r\n");
      out.write("	");
}}
      out.write("\r\n");
      out.write("	\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-danger mx-4\">Delete</button>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container border border-danger\">\r\n");
      out.write(" <div class=\"d-flex m-1 p-1\">\r\n");
      out.write(" <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRL_77dBC3Oj4mQjL1CUJDrmOinbZBxR0PVw&usqp=CAU\" style=\"height: 270px;width:100%;border-radius: 100px 100px;\" alt=\"not found\">\r\n");
      out.write("   </div> \r\n");
      out.write("</div>\r\n");
      out.write("	");


	}
	if(addMach!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Add Machine Data</span>\r\n");
      out.write("      <form method=\"post\" action=\"machReg\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" required oninput=\"trainer()\" name=\"machname\" placeholder=\"Enter Machine Name\" aria-label=\"First name\" >\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-success\">Add Data</button>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	if(mechModify!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Update Machine Data</span>\r\n");
      out.write("      <form method=\"post\" action=\"mechUp\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			    <input type=\"text\" class=\"form-control\" required oninput=\"trainer()\" name=\"machname\" placeholder=\"Enter Machine Name\" aria-label=\"First name\" >\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-warning\">Update</button>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container border border-warning\">\r\n");
      out.write(" <div class=\"d-flex m-1 p-1\">\r\n");
      out.write(" <img src=\"https://www.primalstrength.com/cdn/shop/files/gymdesign_render_Two_collumn_grid_cb1b5850-fa8e-4a7b-a2b3-190c2e45facd.jpg?v=1680719688&width=1500\" style=\"height: 290px;width:100%;border-radius: 30px 30px;\" alt=\"not found\">\r\n");
      out.write("   </div> \r\n");
      out.write("</div>\r\n");
      out.write("	");


	}
	if(mechDel!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Delete Machine Data</span>\r\n");
      out.write("      <form method=\"post\" action=\"mechDelete\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			    <input type=\"text\" required class=\"form-control\" oninput=\"trainer()\" name=\"machId\" placeholder=\"Enter Machine ID\" aria-label=\"First name\" >\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-danger\">Delete</button>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container border border-danger\">\r\n");
      out.write(" <div class=\"d-flex m-1 p-1\">\r\n");
      out.write(" <img src=\"https://dumbbellshub.com/wp-content/uploads/2020/06/Dumbbell-Workouts-for-Mass-scaled.jpg\" style=\"height: 290px;width:100%;border-radius: 30px 30px;\" alt=\"not found\">\r\n");
      out.write("   </div> \r\n");
      out.write("</div>\r\n");
      out.write("	");


	}
	
	if(addMem!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text-info\">\r\n");
      out.write("<h2 class=\"text-center text-info\">Member Details </h2>\r\n");
      out.write("	<form action=\"mReg\" method=\"post\">\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput\" class=\"form-label\">First Name :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"fname\" id=\"fname\" placeholder=\"Enter Your First Name\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Last Name :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"lname\" id=\"lname\" placeholder=\"Enter Your Last Name\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Phone No:</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"con\" id=\"con\" placeholder=\"Enter Your Mobile Number\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Weight :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"w\" id=\"w\" placeholder=\"Enter Your Weight in KG\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\"  class=\"form-label\">Height :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"h\" id=\"h\" placeholder=\"Enter Your Height in feet\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<select class=\"form-select\" name=\"program\" id=\"program\" aria-label=\"Default select example\" required>\r\n");
      out.write("		  <option selected>Select Program</option>\r\n");
      out.write("		  <option value=\"Weight Loss\">Weight Loss</option>\r\n");
      out.write("		  <option value=\"Muscle Gain\">Muscle Gain</option>\r\n");
      out.write("		  <option value=\"Shredding\">Shredding</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Trainer Name :</label>\r\n");
      out.write("		 \r\n");
      out.write("		  <select class=\"form-select\" name=\"tname\" id=\"tname\" aria-label=\"Default select example\" required>\r\n");
      out.write("			  <option selected value=\"\">Select Session :</option>\r\n");
      out.write("			  ");

			  if(tli!=null){
				  for(Trainer t:tli)
				  {
			  
      out.write("\r\n");
      out.write("			  <option name=\"");
      out.print(t.getTname() );
      out.write("\" id=\"");
      out.print(t.getTname() );
      out.write("\" value=\"");
      out.print(t.getTname() );
      out.write('"');
      out.write('>');
      out.print(t.getTname() );
      out.write("</option>\r\n");
      out.write("			 \r\n");
      out.write("	");
}}
      out.write("\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		<select class=\"form-select\" name=\"session\" id=\"session\" aria-label=\"Default select example\" required>\r\n");
      out.write("			  <option selected value=\"\">Select Session :</option>\r\n");
      out.write("			  <option name=\"session\" id=\"session\" value=\"Morning\">Morning</option>\r\n");
      out.write("			  <option name=\"session\" id=\"session\" value=\"Evening\">Evening</option>\r\n");
      out.write("			  \r\n");
      out.write("			</select>\r\n");
      out.write("		<select class=\"form-select my-1\" name=\"membership\" id=\"membership\" aria-label=\"Default select example\">\r\n");
      out.write("			  <option selected value=\"\">Select Membership :</option>\r\n");
      out.write("			  <option name=\"membership\" id=\"membership\" value=\"OneY\">One Year  (80,000 PKR)</option>\r\n");
      out.write("			   <option name=\"membership\" id=\"membership\" value=\"SixM\">Six Months (40,000 PKR)</option>(10,000PKR)\r\n");
      out.write("			  <option  name=\"membership\" id=\"membership\" value=\"ThreeM\">Three Months (20,000 PKR)</option>\r\n");
      out.write("			  <option name=\"membership\" id=\"membership\" value=\"OneM\">One Months (10,000 PKR)</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"d-flex offset-md-5 my-1\">\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"mgen\" id=\"inlineRadio1\" value=\"male\">\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio1\">Male</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"mgen\" id=\"inlineRadio2\" value=\"female\">\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio2\">Female</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"mgen\" id=\"inlineRadio3\" value=\"other\" >\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio3\">Other</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			<div class=\"d-flex offset-md-6 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-success\">Register</button>\r\n");
      out.write("			</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	if(memCheck!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text-info\">\r\n");
      out.write("<h2 class=\"text-center text-info\">Check Member Details </h2>\r\n");
      out.write("	<form action=\"getUpForm\" method=\"post\">\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput\" class=\"form-label\">First Name :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" name=\"fname\" id=\"fname\" placeholder=\"Enter Your First Name\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Last Name :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" name=\"lname\" id=\"lname\" placeholder=\"Enter Your Last Name\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Phone No:</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"con\" id=\"con\" placeholder=\"Enter Your Mobile Number\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"d-flex offset-md-6 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-warning\">Check Data</button>\r\n");
      out.write("			</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	
	if(memdel!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text-info\">\r\n");
      out.write("<h2 class=\"text-center text-info\">Delete Member Details </h2>\r\n");
      out.write("	<form action=\"delMem\" method=\"post\">\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput\" class=\"form-label\">First Name :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" name=\"fname\" id=\"fname\" placeholder=\"Enter Your First Name\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Last Name :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" name=\"lname\" id=\"lname\" placeholder=\"Enter Your Last Name\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Phone No:</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"con\" id=\"con\" placeholder=\"Enter Your Mobile Number\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"d-flex offset-md-6 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-danger\">Delete</button>\r\n");
      out.write("			</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	if(getmemUpForm!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text-info\">\r\n");
      out.write("<h2 class=\"text-center text-info\">Enter New Details </h2>\r\n");
      out.write("	<form action=\"mReg\" method=\"post\">\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput\" class=\"form-label\">First Name :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" name=\"fname\" id=\"fname\" placeholder=\"Enter Your First Name\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Last Name :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" name=\"lname\" id=\"lname\" placeholder=\"Enter Your Last Name\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Phone No:</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"con\" id=\"con\" placeholder=\"Enter Your Mobile Number\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Weight :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"w\" id=\"w\" placeholder=\"Enter Your Weight in KG\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\"  class=\"form-label\">Height :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" oninput=\"input()\" name=\"h\" id=\"h\" placeholder=\"Enter Your Height in feet\" required>\r\n");
      out.write("		</div>\r\n");
      out.write("		<select class=\"form-select\" name=\"program\" id=\"program\" aria-label=\"Default select example\" required>\r\n");
      out.write("		  <option selected>Select Program</option>\r\n");
      out.write("		  <option value=\"Weight Loss\">Weight Loss</option>\r\n");
      out.write("		  <option value=\"Muscle Gain\">Muscle Gain</option>\r\n");
      out.write("		  <option value=\"Shredding\">Shredding</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		<div class=\"mb-3\">\r\n");
      out.write("		  <label for=\"formGroupExampleInput2\" class=\"form-label\">Trainer Name :</label>\r\n");
      out.write("		  <input type=\"text\" class=\"form-control\" name=\"tname\" id=\"tname\" placeholder=\"Enter Your Trainer Name \">\r\n");
      out.write("		</div>\r\n");
      out.write("		<select class=\"form-select\" name=\"session\" id=\"session\" aria-label=\"Default select example\" required>\r\n");
      out.write("			  <option selected value=\"\">Select Session :</option>\r\n");
      out.write("			  <option name=\"session\" id=\"session\" value=\"Morning\">Morning</option>\r\n");
      out.write("			  <option name=\"session\" id=\"session\" value=\"Evening\">Evening</option>\r\n");
      out.write("			  \r\n");
      out.write("			</select>\r\n");
      out.write("		<select class=\"form-select my-1\" name=\"membership\" id=\"membership\" aria-label=\"Default select example\">\r\n");
      out.write("			  <option selected value=\"\">Select Membership :</option>\r\n");
      out.write("			  <option name=\"membership\" id=\"membership\" value=\"OneY\">One Year  (80,000 PKR)</option>\r\n");
      out.write("			   <option name=\"membership\" id=\"membership\" value=\"SixM\">Six Months (40,000 PKR)</option>(10,000PKR)\r\n");
      out.write("			  <option  name=\"membership\" id=\"membership\" value=\"ThreeM\">Three Months (20,000 PKR)</option>\r\n");
      out.write("			  <option name=\"membership\" id=\"membership\" value=\"OneM\">One Months (10,000 PKR)</option>\r\n");
      out.write("			</select>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"d-flex offset-md-5 my-1\">\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"mgen\" id=\"inlineRadio1\" value=\"male\">\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio1\">Male</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"mgen\" id=\"inlineRadio2\" value=\"female\">\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio2\">Female</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-check form-check-inline\">\r\n");
      out.write("				  <input class=\"form-check-input\" type=\"radio\" name=\"mgen\" id=\"inlineRadio3\" value=\"other\" >\r\n");
      out.write("				  <label class=\"form-check-label\" for=\"inlineRadio3\">Other</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			<div class=\"d-flex offset-md-6 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-success\">Update Data</button>\r\n");
      out.write("			</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	if(blist!=null)
	{

      out.write(" \r\n");
      out.write("<h3 class=\"text text-light \">Booking List</h3>\r\n");
      out.write("<thead class=\"text text-center\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th scope=\"col\">ID</th>\r\n");
      out.write("			<th scope=\"col\">Member Name</th>\r\n");
      out.write("			<th scope=\"col\">Machine Name</th>\r\n");
      out.write("			<th scope=\"col\">Session</th>\r\n");
      out.write("		 </tr>\r\n");
      out.write("	 </thead>\r\n");


	for(Machines bm:blist)
	{
		
	
      out.write("\r\n");
      out.write("	<tbody class=\"text text-center text-secondary\">\r\n");
      out.write("        <tr>\r\n");
      out.write("        <th scope=\"row\">");
      out.print(bm.getMid());
      out.write("</th>\r\n");
      out.write("        <td>");
      out.print( bm.getMemname());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print( bm.getMname());
      out.write("</td>	\r\n");
      out.write("		<td>");
      out.print( bm.getBsession());
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("	");


	}
	}
	
	if(mbook!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-1 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Check Machine </span>\r\n");
      out.write("      <form method=\"post\" action=\"mbooking\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			 <div class=\"col-8\" >\r\n");
      out.write("		  <select class=\"form-select \" style=\"height: 40px;width: 70%;\" name=\"mname\" id=\"mname\" aria-label=\"Default select example\"  required>\r\n");
      out.write("			  <option selected value=\"\">Select Machine Name :</option>\r\n");
      out.write("			  ");

			  if(mlishow!=null){
				  for(Machines m:mlishow)
				  {
			  
      out.write("\r\n");
      out.write("			  <option name=\"");
      out.print(m.getMname() );
      out.write("\" id=\"");
      out.print(m.getMname() );
      out.write("\" value=\"");
      out.print(m.getMname() );
      out.write('"');
      out.write('>');
      out.print(m.getMname() );
      out.write("</option>\r\n");
      out.write("			 \r\n");
      out.write("	");
}}
      out.write("\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"col-4\">\r\n");
      out.write("				<div class=\"d-flex offset-md-5\">\r\n");
      out.write("  				<button class=\"btn btn-outline-info\">Check</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	if(mbookingForm!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Book Machine </span>\r\n");
      out.write("      <form method=\"post\" action=\"mbookingDone\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			 <!--  <label class=\"text-warning\">Select Session :</label> -->\r\n");
      out.write("				<select class=\"form-select\" name=\"session\" id=\"session\" aria-label=\"Default select example\" required> \r\n");
      out.write("					<option>Select Session :</option>\r\n");
      out.write("					  <option name=\"session\" id=\"session\" value=\"Morning\">Morning</option>\r\n");
      out.write("					  <option name=\"session\" id=\"session\" value=\"Evening\">Evening</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-secondary\">Book</button>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	
	
	if(cbook!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> Cancel Machine </span>\r\n");
      out.write("      <form method=\"post\" action=\"cbooking\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			 <div class=\"mb-3\">\r\n");
      out.write("		  <select class=\"form-select\" name=\"cid\" id=\"cid\" aria-label=\"Default select example\" required>\r\n");
      out.write("			  <option selected value=\"\">Select AnyOne :</option>\r\n");
      out.write("			  ");

			  if(mbookli!=null){
				  for(Machines mll:mbookli)
				  {
			  
      out.write("\r\n");
      out.write("			  <option name=\"");
      out.print(mll.getMid() );
      out.write("\" id=\"");
      out.print(mll.getMid() );
      out.write("\" value=\"");
      out.print(mll.getMid());
      out.write('"');
      out.write('>');
      out.print(mll.getMemname().toUpperCase());
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(mll.getMname());
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(mll.getBsession());
      out.write("</option>\r\n");
      out.write("			 \r\n");
      out.write("	");
}}
      out.write("\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  					<button class=\"btn btn-outline-danger\">Cancel</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	");


	}
	if(seeReserv!=null)
	{

      out.write(" \r\n");
      out.write("<div class=\"container text text-center text-secondary my-3 \" >\r\n");
      out.write("	<span class=\"fs-3\" style=\"color:green; text-align:left;\"> See Machine Reservation`s </span>\r\n");
      out.write("      <form method=\"post\" action=\"seeRes\" autocomplete=\"on\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("			  <div class=\"col\">\r\n");
      out.write("			 <!--  <label class=\"text-warning\">Select Session :</label> -->\r\n");
      out.write("				<select class=\"form-select\" name=\"seeRes\" id=\"seeRes\" aria-label=\"Default select example\" required> \r\n");
      out.write("					<option>Select Session :</option>\r\n");
      out.write("					  <option name=\"seeRes\" id=\"seeRes\" value=\"Morning\">Morning</option>\r\n");
      out.write("					  <option name=\"seeRes\" id=\"seeRes\" value=\"Evening\">Evening</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"d-flex offset-md-5 my-2\">\r\n");
      out.write("  				<button class=\"btn btn-outline-secondary\">Let`s See</button>\r\n");
      out.write("			</div>\r\n");
      out.write("      </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	");


	}
	
	if(seeList!=null)
	{

      out.write(" \r\n");
      out.write("<h3 class=\"text text-light \">Reservation List</h3>\r\n");
      out.write("<thead class=\"text text-center\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th scope=\"col\">ID</th>\r\n");
      out.write("			<th scope=\"col\">Member Name</th>\r\n");
      out.write("			<th scope=\"col\">Machine Name</th>\r\n");
      out.write("			<th scope=\"col\">Session</th>\r\n");
      out.write("			\r\n");
      out.write("		 </tr>\r\n");
      out.write("	 </thead>\r\n");


	for(Machines mm:seeList)
	{
		
	
      out.write("\r\n");
      out.write("	<tbody class=\"text text-center text-secondary\">\r\n");
      out.write("        <tr>\r\n");
      out.write("        <th scope=\"row\">");
      out.print(mm.getMid());
      out.write("</th>\r\n");
      out.write("        <td>");
      out.print( mm.getMemname());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print( mm.getMname());
      out.write("</td>\r\n");
      out.write("		<td>");
      out.print( mm.getBsession());
      out.write("</td>\r\n");
      out.write("		\r\n");
      out.write("	</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("	");


	}
	}
	
	}catch(Exception e)
	{
		e.printStackTrace();
	}


      out.write("\r\n");
      out.write("	\r\n");
      out.write("	</table>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("*{\r\n");
      out.write("  margin:0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    font-family: sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".contain{\r\n");
      out.write("height: 36px;\r\n");
      out.write("padding: 1px 0px 0px;\r\n");
      out.write("background: none repeat scroll 0% 0% #A3A3A3 ;\r\n");
      out.write("border-top: 1px solid #1885B0;\r\n");
      out.write("font-family: cursive;\r\n");
      out.write("margin-bottom:2px;\r\n");
      out.write("width: 100%;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("color: black;\r\n");
      out.write("margin-left: 0px;\r\n");
      out.write("margin-right: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<br><br>\r\n");
      out.write("	<div class=\"contain fixed-bottom\">\r\n");
      out.write("		Copyright &copy; 2000-");
      out.print( new Date().getYear()+1900 );
      out.write(" by Gym Management Pvt.Ltd.\r\n");
      out.write("	</div>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
