/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2024-03-21 09:41:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.Date;
import javax.xml.crypto.Data;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1711013927886L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1705867853722L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("javax.xml.crypto.Data");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Gym Management</title>\r\n");
      out.write(" <link rel=\"icon\" href=\"img/gm.jpg\" type=\"image/jpg\" />\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"JS/chart.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	/* gets current time */\r\n");
      out.write("		function time() {return document.getElementById(\"tm\").innerText= new Date().toLocaleTimeString();}\r\n");
      out.write("			setInterval(() => {time();}, 1000);\r\n");
      out.write("		\r\n");
      out.write("	/* gets current date */\r\n");
      out.write("		function date() {return document.getElementById(\"dt\").innerHTML= new Date().toDateString()}\r\n");
      out.write("			setInterval(() => {date();}, 1000);\r\n");
      out.write("		\r\n");
      out.write("	</script> -->\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("	\r\n");
      out.write("	#db{\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	height:40px;\r\n");
      out.write("	width:40px;\r\n");
      out.write("	border-radius: 90px 90px;\r\n");
      out.write("	}\r\n");
      out.write("	#tmm{\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	height:50px;\r\n");
      out.write("	width:35px;\r\n");
      out.write("	border-radius: 90px 90px;\r\n");
      out.write("	}\r\n");
      out.write("	body {\r\n");
      out.write("    text-align:start;\r\n");
      out.write("	}\r\n");
      out.write("	.row{\r\n");
      out.write("	display: block;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"text-start\">\r\n");
      out.write("<!-- navbar -->\r\n");
      out.write("<div class=\"sticky-top\">\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg  navbar-dark bg-secondary postion-static\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarTogglerDemo03\" aria-controls=\"navbarTogglerDemo03\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\"><b><i>Gym Management</i></b></a>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo03\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo03\" style=\"width: 250px\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("         <li class=\"nav-item\">\r\n");
      out.write("         <marquee>\r\n");
      out.write("         		<span class=\"text-danger fs-4 modal-dialog modal-sm\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msgReg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("         </marquee>\r\n");
      out.write("        </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/index.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/index.js\"></script>\r\n");
      out.write("<title>Gym Management</title>\r\n");
      out.write("<link rel=\"icon\" href=\"img/gm.jpg\" type=\"image/jpg\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\">\r\n");
      out.write("<tr><td style=\"width: 50%;position:relative; top: 20px;left: 20px;\">\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("	<iframe width=\"900\" height=\"400\" src=\"https://www.youtube.com/embed/eAlNvWgTDZQ\" title=\"Best Hip hop &amp; Trap Workout Music Mix 2021 Neffex &amp; Magic Music Bodybuilding Music\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\r\n");
      out.write("</div></td>\r\n");
      out.write("\r\n");
      out.write("<td align=\"center\" style=\"width: 50%\">\r\n");
      out.write("                \r\n");
      out.write("           <form name=\"\" action=\"login\" method=\"post\" onsubmit=\"return validate()\">\r\n");
      out.write("			<table border=\"0\" width=\"50%\" align=\"center\">\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td colspan=\"2\" align=\"center\">\r\n");
      out.write("						</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("			\r\n");
      out.write("						<tr class=\"td\">\r\n");
      out.write("						 <td colspan=\"2\" align=\"center\">\r\n");
      out.write(" 		                     <img id=\"trans\" src=\"img/gmmm.jpg\" style=\"height: 100px;width: 150px\"></img>\r\n");
      out.write("                        </td>           \r\n");
      out.write("                      </tr>\r\n");
      out.write("                      \r\n");
      out.write("						<tr class=\"td\"><td colspan=\"2\" align=\"center\">\r\n");
      out.write("			");

						try{
						String msg=(String)request.getAttribute("msg");
						if(msg==null){}
						else if(msg.equals("u&p"))
						{		
							out.print("<font color='red' size='3'>Ooop`s! Enter correct username and password</font>");
						}		 
					}catch(Exception a)
							{
						out.print(a);
							}			
				
      out.write("					\r\n");
      out.write("						</td></tr>\r\n");
      out.write("						<tr class=\"td\"><td align=\"center\"><input class=\"input\" autocomplete=\"off\"  placeholder=\"User Name\" type=\"text\" name=\"uname\" id=\"uname\"></td></tr>\r\n");
      out.write("						<tr class=\"td\"><td align=\"center\"><input class=\"input\" autocomplete=\"off\" placeholder=\"Password\" type=\"password\" name=\"pass\" id=\"pass\"></td></tr>\r\n");
      out.write("						<tr></tr>\r\n");
      out.write("						<tr class=\"td\"><td colspan=\"2\"  align=\"center\"><button onchange=\"validate()\">Login</button></td></tr>					\r\n");
      out.write("						</table>            					\r\n");
      out.write("            				</form>	\r\n");
      out.write("            		</td>\r\n");
      out.write("                     \r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("<br><br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("*{\r\n");
      out.write("  margin:0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    font-family: sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".contain{\r\n");
      out.write("height: 36px;\r\n");
      out.write("padding: 1px 0px 0px;\r\n");
      out.write("background: none repeat scroll 0% 0% #A3A3A3 ;\r\n");
      out.write("border-top: 1px solid #1885B0;\r\n");
      out.write("font-family: cursive;\r\n");
      out.write("margin-bottom:2px;\r\n");
      out.write("width: 100%;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("color: black;\r\n");
      out.write("margin-left: 0px;\r\n");
      out.write("margin-right: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<br><br>\r\n");
      out.write("	<div class=\"contain fixed-bottom\">\r\n");
      out.write("		Copyright &copy; 2000-");
      out.print( new Date().getYear()+1900 );
      out.write(" by Gym Management Pvt.Ltd.\r\n");
      out.write("	</div>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
